# Register user

###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "jane Smith",
  "email": "jane@smith.info",
  "password": "Abcd456"
}


# Get all users
###
GET http://localhost:3000/api/users/ HTTP/1.1

# Get single user
###
GET http://localhost:3000/api/users/5f156dfa3ea256cb1e60d729 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1NmYwNWU4MWU2YmNiZWRmMDVmYjMiLCJpYXQiOjE1OTUyNDA1MjIsImV4cCI6MTU5NTI1MDUyMX0.qAYnJt0iUNASPECRSAdCNE2yAZbC3aKWcsUfW8up3Iw

#  Signin route
###
POST http://localhost:3000/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "jane@smith.info",
  "password": "Abcd456"
}